version: "3.8"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - keynow_data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file: .env
    networks:
      - keynow
    ports:
      - '5432:5432'
    expose:
      - '5432'

  rabbit:
    image: rabbitmq:3-management
    restart: unless-stopped
    env_file: .env
    networks:
      - keynow
    ports:
      - "5672:5672"
      - "15672:15672"


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    depends_on:
      - db
      - rabbit
    expose:
      - '8000'
    ports:
      - "8000:8000"
    networks:
      - keynow
    command: >
      sh -c "
        celery -A app.utils.celery worker -l info --concurrency=1 --detach
        gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
      "


volumes:
  keynow_data:

networks:
  keynow:
